name: 'Deploy Tracker Action'
description: 'Deploy Tracker '

inputs:
  dt-access-token:
    description: 'Deploy Tracker Access Token'
    required: true
  application:
    description: 'Application Name'
    required: false
  branch:
    description: 'Branch name'
    required: false
  triggeredBy:
    description: 'Name of the person who triggered the action'
    required: false
  message:
    description: 'Message'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'





